---
action:
  parameters:
    account: s1
    debug: true
    email_from: testingac4me@gmail.com
    email_to:
    - abharast@in.ibm.com
    log_level: DEBUG
    message: |-
      {{trigger}}
      ----------------
      {{trigger.message}}
      ----------------
      {{trigger.message.d.humidity}}
    mime: plain
    subject: monitor_mqtt test email
  ref: email.send_email
context:
  user: st2admin
criteria:
  trigger.message.d.humidity:
    pattern: '80'
    type: gt
  trigger.userdata:
    pattern: abhay
    type: eq
enabled: true
name: mqtt_rule
pack: monitor_mqtt
ref: monitor_mqtt.mqtt_rule
tags: []
trigger:
  parameters: {}
  ref: monitor_mqtt.message
  type: monitor_mqtt.message
type:
  parameters: {}
  ref: standard
uid: rule:monitor_mqtt:mqtt_rule
